version: '3.7'

services:
  #mariadb
  mariadb:
    image: mariadb:sakarkal
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
    - .env
    networks :
    - inception
    restart: always
#nginx
  nginx:
    image: nginx:sakarkal
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    restart: always

#wordpress
  wordpress:
    image: wordpress:sakarkal
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file :
      - .env
    networks:
      - inception
    restart: always


volumes:
  mariadb:
   driver: local
   driver_opts:
      device: $HOME/data/mariadb
      type : none
      o : bind

  wordpress:
    driver: local
    driver_opts:
      device: $HOME/data/wordpress
      type : none
      o : bind

networks:
  inception:
   name: inception